version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - backend_network

  backend:
    image: server-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=mdmxmp
      - DB_PASSWORD=1111
      - DB_NAME=e-store
      - SECRET_KEY=some_secretkey_kek
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mdmxmpmailer@gmail.com
      - SMTP_PASSWORD=htrehcbz
      - API_URL=http://localhost:5000
      - CLIENT_URL=http://localhost:80
    env_file:
      - .env
    volumes:
      - ./server:/app
    depends_on:
      - database
    networks:
      - backend_network

  database:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: e-store
      MYSQL_USER: mdmxmp
      MYSQL_PASSWORD: 1111
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend_network

volumes:
  mariadb_data:

networks:
  backend_network:
    driver: bridge
