version: "3.8"

services:
  backend:
    image: server-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root  # Використовуємо root користувача для підключення
      - DB_PASSWORD=my-secret-pw  # Пароль root користувача
      - DB_NAME=mydatabase
    depends_on:
      - mariadb
    networks:
      - app-network  # Мережа для взаємодії контейнерів

  frontend:
    image: client-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network  # Мережа для взаємодії контейнерів

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw  # Пароль root користувача для MariaDB
      - MYSQL_DATABASE=mydatabase  # Ім'я бази даних
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network  # Мережа для взаємодії контейнерів

volumes:
  mariadb_data:
    driver: local

networks:
  app-network:
    driver: bridge
