version: '3.8'

services:
  database:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: e-store
      MYSQL_USER: mdmxmp
      MYSQL_PASSWORD: 1111
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_container
    restart: always
    depends_on:
      - database
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: mdmxmp
      DB_PASSWORD: 1111
      DB_NAME: e-store
      SECRET_KEY: some_secretkey_kek
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: mdmxmpmailer@gmail.com
      SMTP_PASSWORD: htrehcbz
      API_URL: http://localhost:5000
      CLIENT_URL: http://localhost:3000
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  mariadb_data:

